<style>.task-operation-pill{display:inline-flex;align-items:center;min-height:24px;padding:4px 10px;border-radius:999px;font-size:9px;font-weight:950;letter-spacing:.055em;text-transform:uppercase;border:1px solid transparent;vertical-align:middle;white-space:nowrap}.task-operation-pill-split{color:#6938ef;background:linear-gradient(135deg,#f4f0ff,#ede9fe);border-color:#d9d6fe}.task-operation-pill-swap{color:#175cd3;background:linear-gradient(135deg,#eff8ff,#e6f1ff);border-color:#b2ddff}</style>
@extends('layouts.app')
@section('title','System Activity')
@section('workspace-title','System Activity')
@section('workspace-subtitle','Audit trail of design task pipeline movements')
@section('content')
<div class="page-head"><div><h1>System Activity</h1><p>Pipeline history across the application. {{ number_format($commentCount) }} comments are currently stored.</p></div></div>
<div class="panel"><div class="panel-body"><form method="GET" style="display:flex;gap:9px;margin-bottom:14px"><input class="premium-input" style="max-width:420px" name="search" value="{{ request('search') }}" placeholder="Search Task ID or task name"><button class="btn btn-dark">Search</button></form><div class="activity-list">@forelse($history as $event)<div class="activity-item"><div style="display:flex;justify-content:space-between;gap:10px"><strong>{{ $event->task?->task_id }} · {{ $event->task?->display_task_name }}</strong><span class="badge badge-dark">{{ ucwords(str_replace('_',' ',$event->change_source)) }}</span></div><p>{{ $event->changedBy?->name ?? 'User' }} ({{ ucwords(str_replace('_',' ',$event->changedBy?->role ?? '')) }}) · {{ $event->from_status ? ucwords(str_replace('_',' ',$event->from_status)).' → ' : '' }}{{ ucwords(str_replace('_',' ',$event->to_status)) }} · {{ $event->created_at->format('d M Y') }}</p></div>@empty<div class="empty-state">No activity found.</div>@endforelse</div><div class="pagination-wrap">{{ $history->links() }}</div></div></div>
@endsection
