@extends('layouts.app')
@section('title','User Management')
@section('workspace-title','User Management')
@section('workspace-subtitle','Create, edit and control access for Admin, BD, Designer and Designer Head users')
@section('content')
<div class="page-head"><div><h1>User Management</h1><p>Manage employee accounts and role-based access.</p></div><a href="{{ route('admin.users.create') }}" class="btn btn-primary">＋ Add User</a></div>
<div class="panel"><div class="panel-body">
<form method="GET" class="filter-bar compact" style="margin-bottom:14px"><input class="premium-input" name="search" value="{{ request('search') }}" placeholder="Search name or email"><select class="premium-select" name="role"><option value="">All Roles</option>@foreach(['admin'=>'Admin','bd'=>'BD','designer'=>'Designer','designer_head'=>'Designer Head'] as $k=>$v)<option value="{{ $k }}" @selected(request('role')===$k)>{{ $v }}</option>@endforeach</select><select class="premium-select" name="status"><option value="">All Status</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><button class="btn btn-dark">Filter</button>@if(request()->query())<a class="btn btn-secondary" href="{{ route('admin.users.index') }}">Reset</a>@endif</form>
<div class="table-wrap"><table class="premium-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>@forelse($users as $user)<tr><td><strong>{{ $user->name }}</strong></td><td>{{ $user->email }}</td><td><span class="badge badge-dark">{{ ucwords(str_replace('_',' ',$user->role)) }}</span></td><td><span class="badge {{ $user->is_active ? 'badge-success' : 'badge-danger' }}">{{ $user->is_active ? 'Active' : 'Inactive' }}</span></td><td>{{ $user->created_at?->format('d M Y') }}</td><td><div style="display:flex;gap:6px"><a class="btn btn-secondary" href="{{ route('admin.users.edit',$user) }}">Edit</a>@if(!$user->is(auth()->user()))<form method="POST" action="{{ route('admin.users.toggle',$user) }}">@csrf @method('PATCH')<button class="btn {{ $user->is_active ? 'btn-danger' : 'btn-secondary' }}">{{ $user->is_active ? 'Deactivate' : 'Activate' }}</button></form>@endif</div></td></tr>@empty<tr><td colspan="6" class="empty-state">No users found.</td></tr>@endforelse</tbody></table></div>
<div class="pagination-wrap">{{ $users->links() }}</div></div></div>
@endsection
