@extends('layouts.app')
@section('title','Task Monitoring')
@section('workspace-title','Task Monitoring')
@section('workspace-subtitle','Monitor every design task across BD employees, designers and verticals')
@section('content')
<div class="page-head"><div><h1>Task Monitoring</h1><p>Search and filter the complete design task pipeline.</p></div></div>
<div class="panel"><div class="panel-body">
<form method="GET" class="filter-bar" style="margin-bottom:14px"><input class="premium-input" name="search" value="{{ request('search') }}" placeholder="Search Task ID, task name or client"><select class="premium-select" name="vertical"><option value="">All Verticals</option>@foreach(['outdoor'=>'Outdoor','roadshow'=>'RoadShow','fixtures'=>'Fixtures','signage'=>'Signage','pop_offsets'=>'POP and Offsets','digital_marketing'=>'Digital Marketing','events_activations'=>'Events and Activations'] as $k=>$v)<option value="{{ $k }}" @selected(request('vertical')===$k)>{{ $v }}</option>@endforeach</select><select class="premium-select" name="designer_id"><option value="">All Designers</option>@foreach($designers as $designer)<option value="{{ $designer->id }}" @selected((string)request('designer_id')===(string)$designer->id)>{{ $designer->name }}</option>@endforeach</select><select class="premium-select" name="status"><option value="">All Statuses</option>@foreach($statuses as $k=>$v)<option value="{{ $k }}" @selected(request('status')===$k)>{{ $v }}</option>@endforeach</select><select class="premium-select" name="priority"><option value="">All Priorities</option>@foreach(['urgent'=>'Urgent','high'=>'High','medium'=>'Medium','low'=>'Low'] as $k=>$v)<option value="{{ $k }}" @selected(request('priority')===$k)>{{ $v }}</option>@endforeach</select><button class="btn btn-dark">Filter</button></form>
<div class="table-wrap"><table class="premium-table"><thead><tr><th>Task</th><th>Client</th><th>BD</th><th>Designer</th><th>Vertical</th><th>Priority</th><th>Status</th><th>Due</th><th></th></tr></thead><tbody>@forelse($tasks as $task)<tr><td><strong>{{ $task->task_id }}</strong><div style="margin-top:3px">{{ $task->task_name }}</div></td><td>{{ $task->party_name }}</td><td>{{ $task->assigner?->name ?? '—' }}</td><td>{{ $task->designer?->name ?? '—' }}</td><td>{{ ucwords(str_replace('_',' ',$task->vertical)) }}</td><td><span class="badge priority-{{ $task->priority }}">{{ $task->priority }}</span></td><td><span class="badge badge-dark">{{ $statuses[$task->status] ?? ucwords(str_replace('_',' ',$task->status)) }}</span></td><td>{{ $task->due_at?->format('d M, h:i A') }}</td><td><a class="btn btn-secondary" href="{{ route('admin.tasks.show',$task) }}">View</a></td></tr>@empty<tr><td colspan="9" class="empty-state">No tasks match the selected filters.</td></tr>@endforelse</tbody></table></div><div class="pagination-wrap">{{ $tasks->links() }}</div></div></div>
@endsection
