@extends('layouts.app')
@section('title',$task->task_id)
@section('workspace-title','Task Detail')
@section('workspace-subtitle','Administrative read-only view of task details, comments and pipeline history')
@section('content')
<div class="page-head"><div><h1>{{ $task->task_name }}</h1><p>{{ $task->task_id }} · {{ $statuses[$task->status] ?? ucwords(str_replace('_',' ',$task->status)) }}</p></div><a class="btn btn-secondary" href="{{ route('admin.tasks.index') }}">Back to Tasks</a></div>
<div class="detail-grid">
<div>
<section class="panel"><div class="panel-header"><div class="panel-title">Task Information</div></div><div class="panel-body"><div class="info-grid">@foreach(['Client / Agency'=>ucfirst($task->party_type).' · '.$task->party_name,'Contact'=>$task->contact_person.' · '.$task->mobile_number,'Vertical'=>ucwords(str_replace('_',' ',$task->vertical)),'Task Nature'=>ucwords(str_replace('_',' ',$task->task_nature)),'Priority'=>ucfirst($task->priority),'Designer'=>$task->designer?->name ?? '—','Assigned By'=>$task->assigner?->name ?? '—','Due Date'=>$task->due_at?->format('d M Y, h:i A'),'Total Creatives'=>$task->total_creatives,'Assigned At'=>$task->assigned_at?->format('d M Y, h:i A')] as $k=>$v)<div class="info-item"><span>{{ $k }}</span><strong>{{ $v }}</strong></div>@endforeach</div></div></section>
<section class="panel" style="margin-top:14px"><div class="panel-header"><div class="panel-title">Requirement Details</div></div><div class="panel-body"><div class="requirement-list">@forelse(($task->requirements ?? []) as $key=>$value)<div class="requirement-row"><div class="requirement-key">{{ ucwords(str_replace('_',' ',$key)) }}</div><div>@if(is_array($value)) @if(isset($value['square_feet'])) {{ $value['width'] ?? '' }} × {{ $value['height'] ?? '' }} feet = {{ $value['square_feet'] }} sq.ft @else @foreach($value as $item) @if(is_string($item) && str_contains($item,'/')) <div><a class="file-link" href="{{ Storage::disk('spaces')->url($item) }}" target="_blank">{{ basename($item) }}</a></div> @else <div>{{ is_scalar($item) ? $item : json_encode($item) }}</div> @endif @endforeach @endif @elseif(is_string($value) && str_contains($value,'/')) <a class="file-link" href="{{ Storage::disk('spaces')->url($value) }}" target="_blank">{{ basename($value) }}</a> @else {{ $value }} @endif</div></div>@empty<div class="empty-state">No requirement data available.</div>@endforelse</div></div></section>
</div>
<aside>
<section class="panel"><div class="panel-header"><div class="panel-title">Pipeline History</div></div><div class="panel-body"><div class="activity-list">@forelse($history as $event)<div class="activity-item"><strong>{{ $event->from_status ? ($statuses[$event->from_status] ?? $event->from_status).' → ' : '' }}{{ $statuses[$event->to_status] ?? $event->to_status }}</strong><p>{{ $event->changedBy?->name ?? 'User' }} · {{ $event->created_at->format('d M Y, h:i A') }} · {{ ucwords(str_replace('_',' ',$event->change_source)) }}</p></div>@empty<div class="empty-state">No pipeline activity.</div>@endforelse</div></div></section>
<section class="panel" style="margin-top:14px"><div class="panel-header"><div class="panel-title">Comments</div></div><div class="panel-body"><div class="activity-list">@forelse($comments as $comment)<div class="activity-item"><strong>{{ $comment->user?->name ?? 'User' }}</strong><p style="white-space:pre-wrap">{{ $comment->comment }}</p><p>{{ $comment->created_at->format('d M Y, h:i A') }}</p>@foreach($comment->attachments as $attachment)<div><a class="file-link" href="{{ $attachment->url }}" target="_blank">{{ $attachment->original_name }}</a></div>@endforeach</div>@empty<div class="empty-state">No comments yet.</div>@endforelse</div></div></section>
</aside>
</div>
@endsection
