@extends('layouts.app')
@section('title',$task->task_id)
@section('workspace-title','BD Task Detail')
@section('workspace-subtitle','Review task requirement, designer allocation and current production status')
@section('content')
<div class="page-head"><div><h1>{{ $task->task_name }}</h1><p>{{ $task->task_id }} · {{ ucwords(str_replace('_',' ',$task->status)) }}</p></div><div class="page-actions"><a href="{{ route('bd.tasks.index') }}" class="btn btn-secondary">Back to Assigned Tasks</a><a href="{{ route('bd.tasks.create') }}" class="btn btn-primary">Create New Task</a></div></div>
<div class="detail-grid"><div><section class="panel"><div class="panel-header"><div class="panel-title">Task Information</div></div><div class="panel-body"><div class="info-grid">@foreach(['Client / Agency'=>ucfirst($task->party_type).' · '.$task->party_name,'Contact Person'=>$task->contact_person,'Mobile Number'=>$task->mobile_number,'Vertical'=>ucwords(str_replace('_',' ',$task->vertical)),'Task Nature'=>ucwords(str_replace('_',' ',$task->task_nature)),'Priority'=>ucfirst($task->priority),'Designer'=>$task->designer?->name ?? '—','Total Creatives'=>$task->total_creatives,'Due Date'=>$task->due_at?->format('d M Y, h:i A'),'Assigned At'=>$task->assigned_at?->format('d M Y, h:i A')] as $k=>$v)<div class="info-item"><span>{{ $k }}</span><strong>{{ $v }}</strong></div>@endforeach</div></div></section>
<section class="panel" style="margin-top:14px"><div class="panel-header"><div class="panel-title">Requirement Details</div></div><div class="panel-body"><div class="requirement-list">@forelse(($task->requirements ?? []) as $key=>$value)<div class="requirement-row"><div class="requirement-key">{{ ucwords(str_replace('_',' ',$key)) }}</div><div>@if(is_array($value)) @if(isset($value['square_feet'])) {{ $value['width'] ?? '' }} × {{ $value['height'] ?? '' }} feet = {{ $value['square_feet'] }} sq.ft @else @foreach($value as $item) @if(is_string($item) && str_contains($item,'/'))<div><a class="file-link" href="{{ Storage::disk('spaces')->url($item) }}" target="_blank">{{ basename($item) }}</a></div>@else<div>{{ is_scalar($item) ? $item : json_encode($item) }}</div>@endif @endforeach @endif @elseif(is_string($value) && str_contains($value,'/'))<a class="file-link" href="{{ Storage::disk('spaces')->url($value) }}" target="_blank">{{ basename($value) }}</a>@else{{ $value }}@endif</div></div>@empty<div class="empty-state">No requirement data available.</div>@endforelse</div></div></section></div>
<aside><section class="panel"><div class="panel-header"><div class="panel-title">Current Status</div></div><div class="panel-body"><span class="badge badge-red">{{ ucwords(str_replace('_',' ',$task->status)) }}</span><div class="activity-item" style="margin-top:12px"><strong>Assigned Designer</strong><p>{{ $task->designer?->name ?? '—' }}</p></div><div class="activity-item" style="margin-top:8px"><strong>Due Date</strong><p>{{ $task->due_at?->format('d M Y, h:i A') }}</p></div><div class="activity-item" style="margin-top:8px"><strong>Last Updated</strong><p>{{ $task->updated_at?->diffForHumans() }}</p></div></div></section></aside></div>
@endsection
